services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./porstgres:/var/lib/postgresql/data
    shm_size: 128mb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
